### ISSUE TITLE
Interactions Metric

### ISSUE THREAD

**Issue by bhairavmehta95** [interaction-dataset/interaction-dataset#1]
Do you have code to calculate the interactions metric you use in your paper?

**Comment by bhairavmehta95** [comment]
@m-naumann sorry to tag you, but I imagine sometimes the notifications don't show up (as they don't on my end with some of my repos).

Thanks in advance!

**Comment by m-naumann** [comment]
Thanks for your question. Don't worry about tagging, better safe than sorry ;)

We are currently getting our minds around whether/how to open source the code. We'll get back to you soon.

**Comment by bhairavmehta95** [comment]
Cool, and you wouldn't happen to just have the CSVs of interactions only?

**Comment by m-naumann** [comment]
@bhairavmehta95 sorry for the late reply.

We didn't extract the interaction pairs into separate files, no, sorry.

For the code, we are currently not ready to release it. We hope to do so this year, but we can't promise.

**Comment by bhairavmehta95** [comment]
Ah gotcha. Unforunately I don't think we'll be able to compare against your method in this case; thanks though!
