### ISSUE TITLE
Is there a map conversion tool or a simulator support the interaction-dataset  for RL/IRL training

### ISSUE THREAD

**Issue by Guo-Youtian** [interaction-dataset/interaction-dataset#11]
Hi, I want to use this dataset for RL/IRL training. This requires me to import the dataset into the simulator, such as CARLA or SUMO, but I've been stuck with the Lanelet2 map format conversion problem for a long time. I tried to put the lanelet2 data into the LGSVL simulator and used their covert tools to transform the lanelet2 to opendrive format, but there exist some error after the conversion. So I want to know Is there any map conversion tool or a simulator support directly using the interaction-dataset  for RL/IRL training.  Thanks

**Comment by m-naumann** [comment]
Hi, according to https://www.lgsvlsimulator.com/docs/map-annotation/#map-formats, LGSVL supports lanelet2, so in case you encounter any error during the conversion, I suggest opening an issue there. There is also [coincar-sim](https://github.com/coincar-sim/coincarsim_getting_started), which natively supports lanelet2. It is intended for the use with self-developed agents, though.

Regarding IRL, a simulator is not required, is it?

**Comment by Guo-Youtian** [comment]
> Hi, according to https://www.lgsvlsimulator.com/docs/map-annotation/#map-formats, LGSVL supports lanelet2, so in case you encounter any error during the conversion, I suggest opening an issue there. There is also [coincar-sim](https://github.com/coincar-sim/coincarsim_getting_started), which natively supports lanelet2. It is intended for use with self-developed agents, though.
> 
> Regarding IRL, a simulator is not required, is it?

Thank you for your prompt reply. What you said is correct. IRL does not need simulator support. But without an emulator, many of the state calculation function APIs, such as the geometrical relationship between the ego vehicle and the map, would be lacking. I'm curious if the lanelet2 map has any associated computing libraries.

**Comment by m-naumann** [comment]
There is [lanelet2_matching](https://github.com/coincar-sim/lanelet2_matching) to determine the pose of vehicles within the map, and other than that, lanelet2 is exactly targeted towards the relevant relations for automated driving.

**Comment by Guo-Youtian** [comment]
> There is [lanelet2_matching](https://github.com/coincar-sim/lanelet2_matching) to determine the pose of vehicles within the map, and other than that, lanelet2 is exactly targeted towards the relevant relations for automated driving.

Thanks again. Your answers are really helpful. Now I can write my python scripts and gym env for training.

**Comment by m-naumann** [comment]
Can this issue be closed?
