### ISSUE TITLE
About case_id & frame_id 

### ISSUE THREAD

**Issue by daeunni** [interaction-dataset/interaction-dataset#16]
Hi, thank you for your nice work :) 

I'm using **multi-agent dataset**(https://github.com/interaction-dataset/INTERPRET_challenge_multi-agent), and I have some questions about case_id & frame_id. 

1. I'm curious about the exact definition of **case_id**. Is case_id **continuous** within one dataset? For example, can the next scene of case_id=1 be understood as case_id=2?

2. Is it right that **track_id (agent_id) is not unique** in one dataset? I checked that track_id is 4 in DR_USA_Roundabout_SR test data and the agent type has car and pedestrian at the same time.

3. How was **the total number of vehicles** of TABLE 2(the summary of data) on your paper (https://arxiv.org/pdf/1910.03088.pdf) calculated?

Thank you in advance.
Sincerely.

**Comment by minhaj6** [comment]
I have same questions! 
@daeunni if you have figured it out, please share.
