### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by ehsan-ami** [interaction-dataset/interaction-dataset#17]
Hi,

Could you please put an open-source license to this repo and to the other interaction-dataset-related repositories? This helps others to be able to use your repo/dataset in other projects doubtlessly.

For instance, this repositories has also the same issue:
* [INTERPRET_challenge_regular_generalizability_track](https://github.com/interaction-dataset/INTERPRET_challenge_regular_generalizability_track)

Thanks!

**Comment by m-naumann** [comment]
good point, see #18 (I need the colleagues from UC Berkeley to confirm)
