### ISSUE TITLE
How to convert osm data into opendrive(xodr) data?

### ISSUE THREAD

**Issue by gaoyinfeng** [interaction-dataset/interaction-dataset#2]
I tried to use SUMO to convert osm files from INTERACTION dataset, but encountered an error:

  Error: No nodes loaded.
  Quitting (on error).

I also tried to convert other osm files from [www.openstreetmap.org](url), and it worked. I guess the problem is that Lanelet2 uses a different way to represent roads compared with other osm generators.
So it's there a method I can use to convert osm data from INTERACTION dataset into opendrive(xodr) data? Your help will be very much appreciated.

**Comment by m-naumann** [comment]
Sorry for the late reply. You are right, lanelet2 uses the osm-Syntax but the content largely differs. Currently, I'm not aware of converters that are available open-source, you could ask here though: https://github.com/fzi-forschungszentrum-informatik/Lanelet2

**Comment by gaoyinfeng** [comment]
Thank you for your reply. I have another question: currently I'm working on applying IRL algorithms in CARLA simulator, due to the map convert problem, it seems hard to achieve for now. So I want to ask: what do you usually do to use Interaction dataset in your reaserch? Your answer will be very much appreciated!

**Comment by m-naumann** [comment]
Well, you can use it in many ways, we gave some examples in the paper which can be found here: https://interaction-dataset.com/ 
IRL is one application. If you need a simulator supporting lanelet2, have a look at https://github.com/coincar-sim/coincarsim_getting_started

**Comment by gaoyinfeng** [comment]
Thanks! I will have a look.

**Comment by ShenZC25** [comment]
> I tried to use SUMO to convert osm files from INTERACTION dataset, but encountered an error:
> 
> Error: No nodes loaded. Quitting (on error).
> 
> I also tried to convert other osm files from [www.openstreetmap.org](url), and it worked. I guess the problem is that Lanelet2 uses a different way to represent roads compared with other osm generators. So it's there a method I can use to convert osm data from INTERACTION dataset into opendrive(xodr) data? Your help will be very much appreciated.

Hello, have you solved this problem? I'm also using SUMO to simulate and learn the Interaction data set. How did you solve this problem? Could you add QQ to communicate? My QQ: 1968310559
