### ISSUE TITLE
Failed to import module "pyproj" in certain file

### ISSUE THREAD

**Issue by OscarWan** [interaction-dataset/interaction-dataset#3]
Hi! When I was doing the setup of this visualization, I failed to build Lanelet2 ( I've posted the issue under that repository, link: https://github.com/fzi-forschungszentrum-informatik/Lanelet2/issues/110). Then I installed module "pyproj" and the terminal check showed it's ok to use. But when I run the test and main file, the error shows that no module named pyproj. Basically, I think it might be the path problem so that main file cannot find the module. Could you help me to figure it out the possible mistakes? Thanks!

The running log for test file:
```
$ ./test_imports.py 
Trying to import csv (for loading track files).
ok

Trying to import lanelet2 (for loading maps).
Could not import lanelet2. It must be built and sourced, see https://github.com/fzi-forschungszentrum-informatik/Lanelet2 for details.For visualization, the fallback is utils.map_vis_without_lanelet.py.

Trying to import xml (for loading maps without lanelet2).
ok

Trying to import pyproj (for loading maps without lanelet2).
Could not import pyproj.
  Since lanelet2 also does not work, you need to install this to be able to load and visualize maps.

Trying to import argparse (argument parsing for loading and visualizing tracks).
ok

Trying to import os (check file existence for loading and visualizing tracks).
ok

Trying to import time (for scenario playback).
ok

Trying to import math (for visualizing tracks).
ok

Trying to import matplotlib (for visualizing tracks).
ok

Trying to import numpy (for visualizing tracks).
ok
```
When I try to import the module through terminal outside the file:
```
$ python 
Python 3.7.3 (default, Mar  6 2020, 22:34:30) 
[Clang 11.0.3 (clang-1103.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyproj
>>>exit()
```
I also put the python here:
```
$ which -a python
python: aliased to /usr/bin/python3
/usr/bin/python
/usr/bin/python
```

**Comment by m-naumann** [comment]
Hi Oscar, the test module actually reports a problem: 

```
Trying to import pyproj (for loading maps without lanelet2).
Could not import pyproj.
  Since lanelet2 also does not work, you need to install this to be able to load and visualize maps.
```

So you have to install pyproj first.

**Comment by m-naumann** [comment]
@OscarWan Is this issue resolved?

**Comment by OscarWan** [comment]
Oh, thanks for concerning about it! I think there might be some problem related to Mac OS Catalina so that the terminal got a wrong path when calling import function. I am trying to figure the OS problem first and then I think the installed pyproj can be used.
