### ISSUE TITLE
Pedestrian data

### ISSUE THREAD

**Issue by semmelknoedel** [interaction-dataset/interaction-dataset#6]
Hi,

In your new code there are also pedestrian files mentioned. Are these part of the Interaction dataset? I've got the dataset a while ago and there is no pedestrian file included.

Thanks,
Barbara

**Comment by m-naumann** [comment]
Hi Barbara,

Thanks for your interest. The pedestrian data was not part of your version, but was/will be added to the dataset. @litingsun @ZHAN-Wei can you give details on that?

Best,
Max

**Comment by m-naumann** [comment]
Meanwhile, the pedestrian data is included in the dataset, sorry for the late reply
