### ISSUE TITLE
How you have converted longitude and latitude to local xy coordinates?

### ISSUE THREAD

**Issue by arvindkyutech** [interaction-dataset/interaction-dataset#7]
Can you please share, how you have converted your collected longitude, latitude to xy coordinates. Is it different from UTM?

**Comment by m-naumann** [comment]
Hi @arvindkyutech 

thanks for your interest. We didn't actually collect lat/lon data, but used a plane assumption in the drone images. 

The transformation from x/y to lat/lon for storing the data was performed using UTM, particularly this implementatoin: https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_projection/src/UTM.cpp
If you just use the provided scripts, they will provide the original x/y to you.

Does that answer your question?

**Comment by arvindkyutech** [comment]
Thank for your reply.
Got the point.
