### ISSUE TITLE
Meaning of tags in map data

### ISSUE THREAD

**Issue by myunghakLee** [interaction-dataset/interaction-dataset#8]
I know that there are the following tags in the map data.

	'pedestrian_marking', 'stop_line', 'curbstone', 'road_border', 'line_thick', 'line_thin', 'guard_rail', 'virtual', 'traffic_sign'
	'usR1-1', 'solid_solid', 'low', 'solid'

Some of these are understandable, but others are not certain.
Can I ask what the tags below mean?

	'line_thick'
	'line_thin'
	'virtual'
	'usR1-1'
	'solid_solid'
	'low'
	'solid'
	'road_border'

**Comment by m-naumann** [comment]
The map is provided in lanelet2 format, see https://github.com/fzi-forschungszentrum-informatik/Lanelet2

The tags that confuse you are explained here:
https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/doc/LinestringTagging.md

If you have further questions about them, please open an issue in lanelet2 and refer to it here.

Thanks

**Comment by myunghakLee** [comment]
Thank you very much!!!

**Comment by m-naumann** [comment]
I guess this can be closed, feel free to reopen otherwise
